version: '3.1'
services:
  world_x:
    image: mysql
    environment:
      MYSQL_DATABASE: 'demo_accounts' # Make sure it's surrounded by single quotes
      MYSQL_ROOT_PASSWORD: 7812
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-volume: